SET SERVEROUTPUT ON;
-- DECLARATION SECTION (OPTIONAL)
DECLARE
	v_test VARCHAR2(15) := 'Initial Value';
	v_test1 VARCHAR2(15); 

-- EXECUTION SECTION (MANDATORY)
BEGIN
	v_test1 := 'Oracle';
	DBMS_OUTPUT.PUT_LINE(v_test1);
	
END

-- EXCEPTION-HANDLING SECTION (OPTIONAL)


